# Generated by Django 5.0.1 on 2024-10-19 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('price', models.CharField(max_length=50)),
                ('url', models.URLField()),
                ('store', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=100)),
                ('date_scrapping', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
