# Generated by Django 5.0.1 on 2024-10-20 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0002_product_saved_by_alter_product_price_pricehistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='url',
            field=models.URLField(max_length=400),
        ),
    ]
