# Generated by Django 5.0.1 on 2024-10-22 01:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0004_alter_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='img_url',
            field=models.URLField(default=0, max_length=400),
            preserve_default=False,
        ),
    ]
