# Generated by Django 5.0.1 on 2024-10-22 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0005_product_img_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='discount',
            field=models.IntegerField(default=3, max_length=4),
            preserve_default=False,
        ),
    ]
